(in-package :su-real)

;; @author Luca Krohm
(def-fact-group suturo-action (desig:action-grounding)
  ;; @author Luca Krohm
  (<- (action-grounding ?designator (su-real:pick-up ?resolved-action-designator))
    (spec:property ?designator (:type :picking-up))
    (once (or (desig:desig-prop ?designator (:collision-mode ?collision-mode))
              (equal ?collision-mode nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-b ?collision-object-b))
              (equal ?collision-object-b nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-b-link
                                             ?collision-object-b-link))
              (equal ?collision-object-b-link nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-a ?collision-object-a))
              (equal ?collision-object-a nil)))
    (once (or (desig:desig-prop ?designator (:object-type ?object-type))
              (equal ?object-type nil)))
    (once (or (desig:desig-prop ?designator (:goal-pose ?goal-pose))
              (equal ?goal-pose nil)))
    (once (or (desig:desig-prop ?designator (:object-size ?object-size))
              (equal ?object-size nil)))
    (once (or (desig:desig-prop ?designator (:object-shape ?object-shape))
              (equal ?object-shape nil)))
    (once (or (desig:desig-prop ?designator (:object-name ?object-name))
              (equal ?object-name nil)))
    (once (or (desig:desig-prop ?designator (:from-above ?from-above))
              (equal ?from-above nil)))
    (once (or (desig:desig-prop ?designator (:sequence-goal ?sequence-goal))
              (equal ?sequence-goal nil)))

    (desig:designator :action ((:type :picking-up)
                               (:collision-mode ?collision-mode)
                               (:collision-object-b ?collision-object-b)
                               (:collision-object-b-link ?collision-object-b-link)
                               (:collision-object-a ?collision-object-a)
                               (:object-type ?object-type)
                               (:goal-pose ?goal-pose)
                               (:object-size ?object-size)
                               (:object-shape ?object-shape)
                               (:object-name ?object-name)
                               (:from-above ?from-above)
                               (:sequence-goal ?sequence-goal)
                               )
                      ?resolved-action-designator))

  ;; @author Luca Krohm
  (<- (action-grounding ?designator (su-real:place ?resolved-action-designator))
    (spec:property ?designator (:type :placing))
    (once (or (desig:desig-prop ?designator (:collision-mode ?collision-mode))
              (equal ?collision-mode nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-b ?collision-object-b))
              (equal ?collision-object-b nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-b-link
                                             ?collision-object-b-link))
              (equal ?collision-object-b-link nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-a ?collision-object-a))
              (equal ?collision-object-a nil)))
    (once (or (desig:desig-prop ?designator (:goal-pose ?goal-pose))
              (equal ?goal-pose nil)))
    (once (or (desig:desig-prop ?designator (:object-size ?object-size))
              (equal ?object-size nil)))
    (once (or (desig:desig-prop ?designator (:from-above ?from-above))
              (equal ?from-above nil)))
    (once (or (desig:desig-prop ?designator (:neatly ?neatly))
              (equal ?neatly nil)))
    (once (or (desig:desig-prop ?designator (:inside ?inside))
              (equal ?inside nil)))
    (once (or (desig:desig-prop ?designator (:sequence-goal ?sequence-goal))
              (equal ?sequence-goal nil)))

    (desig:designator :action ((:type :placing)
                               (:collision-mode ?collision-mode)
                               (:collision-object-b ?collision-object-b)
                               (:collision-object-b-link ?collision-object-b-link)
                               (:collision-object-a ?collision-object-a)
                               (:goal-pose ?goal-pose)
                               (:object-size ?object-size)
                               (:from-above ?from-above)
                               (:neatly ?neatly)
                               (:inside ?inside)
                               (:sequence-goal ?sequence-goal))
                      ?resolved-action-designator))

   ;; @author Luca Krohm
  (<- (action-grounding ?designator (su-real:open-door ?resolved-action-designator))
    (spec:property ?designator (:type :opening-door))
    (once (or (desig:desig-prop ?designator (:collision-mode ?collision-mode))
              (equal ?collision-mode nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-b ?collision-object-b))
              (equal ?collision-object-b nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-b-link
                                             ?collision-object-b-link))
              (equal ?collision-object-b-link nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-a ?collision-object-a))
              (equal ?collision-object-a nil)))
    (once (or (desig:desig-prop ?designator (:handle-link ?handle-link))
              (equal ?handle-link nil)))
    (once (or (desig:desig-prop ?designator (:handle-pose ?handle-pose))
              (equal ?handle-pose nil)))
    (once (or (desig:desig-prop ?designator (:joint-angle ?joint-angle))
              (equal ?joint-angle nil)))

    (desig:designator :action ((:type :opening-door)
                               (:collision-mode ?collision-mode)
                               (:collision-object-b ?collision-object-b)
                               (:collision-object-b-link ?collision-object-b-link)
                               (:collision-object-a ?collision-object-a)
                               (:handle-link ?handle-link)
                               (:handle-pose ?handle-pose)
                               (:joint-angle ?joint-angle))
                      ?resolved-action-designator))

  ;; @author Luca Krohm
  (<- (action-grounding ?designator (su-real:su-pour ?resolved-action-designator))
    (spec:property ?designator (:type :su-pouring))
    (once (or (desig:desig-prop ?designator (:collision-mode ?collision-mode))
              (equal ?collision-mode nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-b ?collision-object-b))
              (equal ?collision-object-b nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-b-link
                                             ?collision-object-b-link))
              (equal ?collision-object-b-link nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-a ?collision-object-a))
              (equal ?collision-object-a nil)))
    (once (or (desig:desig-prop ?designator (:object-size ?object-size))
              (equal ?object-size nil)))
    (once (or (desig:desig-prop ?designator (:target-object ?target-object))
              (equal ?target-object nil)))
    (once (or (desig:desig-prop ?designator (:target-size ?target-size))
              (equal ?target-size nil)))
    (once (or (desig:desig-prop ?designator (:target-name ?target-name))
              (equal ?target-name nil)))
    (once (or (desig:desig-prop ?designator (:sequence-goal ?sequence-goal))
              (equal ?sequence-goal nil)))

    (desig:designator :action ((:type :su-pouring)
                               (:collision-mode ?collision-mode)
                               (:collision-object-b ?collision-object-b)
                               (:collision-object-b-link ?collision-object-b-link)
                               (:collision-object-a ?collision-object-a)
                               (:object-size ?object-size)
                               (:target-object ?target-object)
                               (:target-size ?target-size)
                               (:target-name ?target-name)
                               (:sequence-goal ?sequence-goal))
                      ?resolved-action-designator))


  (<- (action-grounding ?designator (su-real::sequence-goal-original ?resolved-action-designator))
    (spec:property ?designator (:type :sequence-goal-original))
    (once (or (desig:desig-prop ?designator (:action ?action))
              (equal ?action nil)))
    (once (or (desig:desig-prop ?designator (:motions ?motions))
              (equal ?motions nil)))
    (once (or (desig:desig-prop ?designator (:collision-mode ?collision-mode))
              (equal ?collision-mode nil)))
    (once (or (desig:desig-prop ?designator (:object-type ?object-type))
              (equal ?object-type nil)))
    (once (or (desig:desig-prop ?designator (:goal-pose ?goal-pose))
              (equal ?goal-pose nil)))
    (once (or (desig:desig-prop ?designator (:object-height ?object-height))
              (equal ?object-height nil)))
    (once (or (desig:desig-prop ?designator (:object-size ?object-size))
              (equal ?object-size nil)))
    (once (or (desig:desig-prop ?designator (:object-shape ?object-shape))
              (equal ?object-shape nil)))
    (once (or (desig:desig-prop ?designator (:object-name ?object-name))
              (equal ?object-name nil)))
    (once (or (desig:desig-prop ?designator (:from-above ?from-above))
              (equal ?from-above nil)))
    (once (or (desig:desig-prop ?designator (:target-object ?target-object))
              (equal ?target-object nil)))
    (once (or (desig:desig-prop ?designator (:target-size ?target-size))
              (equal ?target-size nil)))
    (once (or (desig:desig-prop ?designator (:target-name ?target-name))
              (equal ?target-name nil)))
    (once (or (desig:desig-prop ?designator (:tilt-direction ?tilt-direction))
              (equal ?tilt-direction nil)))
    (once (or (desig:desig-prop ?designator (:tilt-angle ?tilt-angle))
              (equal ?tilt-angle nil)))
    (once (or (desig:desig-prop ?designator (:reference-frame ?reference-frame))
              (equal ?reference-frame nil)))
    (once (or (desig:desig-prop ?designator (:gripper-state ?gripper-state))
              (equal ?gripper-state nil)))
    (once (or (desig:desig-prop ?designator (:pose-keyword ?pose-keyword))
              (equal ?pose-keyword nil)))

    (desig:designator :action ((:type :sequence-goal-original)
                               (:action ?action)
                               (:motions ?motions)
                               (:collision-mode ?collision-mode)
                               (:object-type ?object-type)
                               (:goal-pose ?goal-pose)
                               (:object-height ?object-height)
                               (:object-size ?object-size)
                               (:object-shape ?object-shape)
                               (:object-name ?object-name)
                               (:from-above ?from-above)
                               (:target-object ?target-object)
                               (:target-size ?target-size)
                               (:target-name ?target-name)
                               (:tilt-angle ?tilt-angle)
                               (:tilt-direction ?tilt-direction)
                               (:reference-frame ?reference-frame)
                               (:gripper-state ?gripper-state)
                               (:pose-keyword ?pose-keyword)
                               (:distance ?distance)
                               )
                      ?resolved-action-designator))

  (<- (desig:action-grounding ?designator (su-real:sequence-goal ?resolved-action-designator))
    (spec:property ?designator (:type :sequence-goal))
    (desig:desig-prop ?designator (:action ?action))

    (-> (desig:desig-prop ?designator (:motions ?motions))
        (lisp-fun su-real::get-all-attributes ?motions
                  ?attributes)
        (and (format "WARNING: Please specify a motion sequence.~%")
             (fail)))
    
    (once (or (desig:desig-prop ?designator (:collision-mode ?collision-mode))
              (equal ?collision-mode :allow-all)))
    
    (-> (member :object-name ?attributes)
        (or (desig:desig-prop ?designator (:object-name ?object-name))
            (and (format "WARNING: Please specify the objectname.~%")
                 (fail)))
        (equal ?object-name nil))

    (-> (member :object-size ?attributes)
        (once (or (desig:desig-prop ?designator (:object-size ?object-size))
                  (lisp-fun su-real::get-object-size ?object-name
                            ?object-size)))
        (equal ?object-size nil))

    (-> (member :goal-pose ?attributes)
        (once (or (desig:desig-prop ?designator (:goal-pose ?goal-pose))
                  (lisp-fun su-real::get-goal-pose ?object-name
                            ?goal-pose)))
        (equal ?goal-pose nil))

    (-> (member :tilt-angle ?attributes)
        (or (desig:desig-prop ?designator (:tilt-angle ?tilt-angle))
            (and (format "WARNING: Please specify the tilt-angle.~%")
                 (fail)))
        (equal ?tilt-angle nil))

    (-> (member :tilt-direction ?attributes)
        (or (desig:desig-prop ?designator (:tilt-direction ?tilt-direction))
            (and (format "WARNING: Please specify the tilt-direction.~%")
                 (fail)))
        (equal ?tilt-direction nil))

    (-> (member :reference-frame ?attributes)
        (or (desig:desig-prop ?designator (:reference-frame ?reference-frame))
            (and (format "WARNING: Please specify the reference-frame.~%")
                 (fail)))
        (equal ?reference-frame nil))

    (-> (member :gripper-state ?attributes)
        (or (desig:desig-prop ?designator (:gripper-state ?gripper-state))
            (and (format "WARNING: Please specify the gripper-state.~%")
                 (fail)))
        (equal ?gripper-state nil))

    (-> (member :pose-keyword ?attributes)
        (or (desig:desig-prop ?designator (:pose-keyword ?pose-keyword))
            (and (format "WARNING: Please specify the pose-keyword.~%")
                 (fail)))
        (equal ?pose-keyword nil))

    (-> (member :distance ?attributes)
        (or (desig:desig-prop ?designator (:distance ?distance))
            (and (format "WARNING: Please specify the distance.~%")
                 (fail)))
        (equal ?distance nil))
    
    (-> (member :context ?attributes)
        (and (once (or (desig:desig-prop ?designator (:from-above ?from-above))
                       (lisp-fun su-real::get-from-above ?object-name
                                 ?from-above)))
             (once (or (desig:desig-prop ?designator (:neatly ?neatly))
                       (lisp-fun su-real::get-neatly ?object-name
                                 ?neatly)))
             (once (or (desig:desig-prop ?designator (:object-type ?object-type))
                       (lisp-fun su-real::get-object-type ?object-name
                                 ?object-type)))
             (once (or (desig:desig-prop ?designator (:object-shape ?object-shape))
                       (lisp-fun su-real::get-object-shape ?object-name
                                 ?object-shape)))
             
             (lisp-fun su-real::generate-context ?action ?motions :from-above ?from-above
                                                                  :neatly ?neatly
                                                                  :object-type ?object-type
                                                                  :object-shape ?object-shape
                                                                  ?context))
        (equal ?context nil))

    (lisp-fun su-real::generate-motion-sequence ?motions ?context :goal-pose ?goal-pose
                                                                  :object-name ?object-name
                                                                  :object-size ?object-size
                                                                  :tilt-angle ?tilt-angle
                                                                  :tilt-direction ?tilt-direction
                                                                  :reference-frame ?reference-frame
                                                                  :gripper-state ?gripper-state
                                                                  :pose-keyword ?pose-keyword
                                                                  :distance ?distance
                                                                  ?motion-sequence)

    (desig:designator :action ((:type :sequence-goal)
                               (:motion-sequence ?motion-sequence)
                               (:collision-mode ?collision-mode))
                      ?resolved-action-designator))

  (<- (action-grounding ?designator (su-real:take-pose ?resolved-action-designator))
    (spec:property ?designator (:type :taking-pose))
    (once (or (desig:desig-prop ?designator (:pose-keyword ?pose-keyword))
              (equal ?pose-keyword nil)))
    (once (or (desig:desig-prop ?designator (:head-pan ?head-pan))
              (equal ?head-pan nil)))
    (once (or (desig:desig-prop ?designator (:head-tilt ?head-tilt))
              (equal ?head-tilt nil)))
    (once (or (desig:desig-prop ?designator (:arm-lift ?arm-lift))
              (equal ?arm-lift nil)))
    (once (or (desig:desig-prop ?designator (:arm-flex ?arm-flex))
              (equal ?arm-flex nil)))
    (once (or (desig:desig-prop ?designator (:arm-roll ?arm-roll))
              (equal ?arm-roll nil)))
    (once (or (desig:desig-prop ?designator (:wrist-flex ?wrist-flex))
              (equal ?wrist-flex nil)))
    (once (or (desig:desig-prop ?designator (:wrist-roll ?wrist-roll))
              (equal ?wrist-roll nil)))

    (desig:designator :action ((:type :taking-pose)
                               (:pose-keyword ?pose-keyword)
                               (:head-pan ?head-pan)
                               (:head-tilt ?head-tilt)
                               (:arm-lift ?arm-lift)
                               (:arm-flex ?arm-flex)
                               (:arm-roll ?arm-roll)
                               (:wrist-flex ?wrist-flex)
                               (:wrist-roll ?wrist-roll)
                               )
                      ?resolved-action-designator))
)
